"""initial_schema

Revision ID: b57303267a7c
Revises: 
Create Date: 2026-03-13 12:34:42.490914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b57303267a7c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lyrics', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_lyrics_user_id'), 'lyrics', ['user_id'], unique=False)
    op.alter_column('resources', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_resources_user_id'), 'resources', ['user_id'], unique=False)
    op.alter_column('stories', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stories', 'audio_file_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_stories_user_id'), 'stories', ['user_id'], unique=False)
    op.drop_column('stories', 'audio')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'google_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.alter_column('visuals', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_visuals_user_id'), 'visuals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visuals_user_id'), table_name='visuals')
    op.alter_column('visuals', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'google_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('stories', sa.Column('audio', sa.TEXT(), nullable=True))
    op.drop_index(op.f('ix_stories_user_id'), table_name='stories')
    op.alter_column('stories', 'audio_file_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('stories', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_resources_user_id'), table_name='resources')
    op.alter_column('resources', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_lyrics_user_id'), table_name='lyrics')
    op.alter_column('lyrics', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
