"""add_shadowing_tables

Revision ID: d4e5f6a7b8c9
Revises: c3f7a1d9e5b8
Create Date: 2026-03-13 23:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import func
from datetime import datetime
import uuid


# revision identifiers, used by Alembic.
revision: str = 'd4e5f6a7b8c9'
down_revision: Union[str, Sequence[str], None] = 'c3f7a1d9e5b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create shadowing_sessions table
    op.create_table('shadowing_sessions',
        sa.Column('id', sa.String(36), nullable=False, primary_key=True),
        sa.Column('user_id', sa.String(36), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('theme', sa.String(255), nullable=False),
        sa.Column('language', sa.String(100), nullable=False, server_default='en'),
        sa.Column('created_at', sa.DateTime, nullable=False, server_default=func.now()),
        sa.Column('completed_at', sa.DateTime, nullable=True),
    )
    op.create_index('ix_shadowing_sessions_user_created', 'shadowing_sessions', ['user_id', 'created_at'])

    # Create shadowing_attempts table
    op.create_table('shadowing_attempts',
        sa.Column('id', sa.String(36), nullable=False, primary_key=True),
        sa.Column('session_id', sa.String(36), sa.ForeignKey('shadowing_sessions.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('phrase_id', sa.Integer, nullable=False),
        sa.Column('phrase_text', sa.Text, nullable=False),
        sa.Column('accuracy_score', sa.Float, nullable=False, server_default='0.0'),
        sa.Column('words_matched', sa.Integer, nullable=False, server_default='0'),
        sa.Column('total_words', sa.Integer, nullable=False, server_default='0'),
        sa.Column('attempted_at', sa.DateTime, nullable=False, server_default=func.now()),
    )
    op.create_index('ix_shadowing_attempts_session', 'shadowing_attempts', ['session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shadowing_attempts')
    op.drop_table('shadowing_sessions')
    # ### end Alembic commands ###
